name: Nightly Build
on:
  push:
    branches:
      - '**'

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup
        shell: bash
        run: |
          sudo apt-get install \
            libx11-dev:amd64 \
            libxtst-dev:amd64 \
            libxt-dev:amd64 \
            libxinerama-dev:amd64 \
            libx11-xcb-dev:amd64 \
            libxkbcommon-dev:amd64 \
            libxkbcommon-x11-dev:amd64 \
            libxkbfile-dev:amd64

      - name: Compile
        env:
          CC: x86_64-linux-gnu-gcc
          CFLAGS: '-O2 -march=x86-64 -mtune=generic -g -fomit-frame-pointer -flto -fno-stack-protector -pipe'
          LDFLAGS: '-fuse-ld=gold -Wl,-O1 -Wl,--as-needed'
          PKG_CONFIG_PATH: '/usr/lib/x86_64-linux-gnu/pkgconfig'
        shell: bash
        run: |
          cmake -B ${{github.workspace}}/build \
            -G "Unix Makefiles" \
            -D CMAKE_INSTALL_PREFIX=${{github.workspace}}/dist/linux/x86_64 \
            -D CMAKE_VERBOSE_MAKEFILE=true \
            -D BUILD_SHARED_LIBS=ON \
            -D BUILD_DEMO=ON

          cmake --build ${{github.workspace}}/build \
            --parallel 2 \
            --config RelWithDebInfo \
            --clean-first

          cmake --install ${{github.workspace}}/build --config RelWithDebInfo

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: nightly-build
          path: ${{github.workspace}}/dist/**/*

